// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5-T7zlKM8x2dIee_HCZX9wvYmBiOgFHI',
    appId: '1:388124300819:web:c1fda5e7250a42f16a51e6',
    messagingSenderId: '388124300819',
    projectId: 'gestion-driver',
    authDomain: 'gestion-driver.firebaseapp.com',
    storageBucket: 'gestion-driver.firebasestorage.app',
    measurementId: 'G-5BDCJEP3E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2FoyNaULsy95e2qse-wQWZ_MdZ7X1Ytc',
    appId: '1:388124300819:android:0310049b4fcec1576a51e6',
    messagingSenderId: '388124300819',
    projectId: 'gestion-driver',
    storageBucket: 'gestion-driver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxttOB4E30w9B9RYRYw5lriYFV5oYMsts',
    appId: '1:388124300819:ios:a7d88feab9e5c1e96a51e6',
    messagingSenderId: '388124300819',
    projectId: 'gestion-driver',
    storageBucket: 'gestion-driver.firebasestorage.app',
    iosBundleId: 'com.example.gestionDriver',
  );
}
